###CREATE
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "George Mendez",
    "age": 80,
    "email": "Geor@gmail.com"

}

###SEACHE ALL
GET http://localhost:9000/api/users HTTP/1.1

###SEACH ONE
GET http://localhost:9000/api/users/6453c8463bed5591348fd890 HTTP/1.1

###uptdate a user
PUT http://localhost:9000/api/users/6473291fab0cb3c897cd7c2c HTTP/1.1
Content-Type: application/json

{
    "name": "Marta Sanz",
    "age": 56,
    "email": "martaSan@gmail.com"

}

###Delete
DELETE http://localhost:9000/api/users/64732af6ab0cb3c897cd7c30 HTTP/1.1